// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy9-NujRxhwQNKbRL-LEJw7j3P9FemHXw',
    appId: '1:796449605451:web:6a025ab68fe179636f8ace',
    messagingSenderId: '796449605451',
    projectId: 'first-app-98ad4',
    authDomain: 'first-app-98ad4.firebaseapp.com',
    storageBucket: 'first-app-98ad4.appspot.com',
    measurementId: 'G-YZ3CCMKNS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDchEiFI-RCVbc01xcPVYImwZLw4J92e6w',
    appId: '1:796449605451:android:91f013cedb3f13426f8ace',
    messagingSenderId: '796449605451',
    projectId: 'first-app-98ad4',
    storageBucket: 'first-app-98ad4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuqWW9zZRsHjRuUJNzrcqkD8esPhgTsmA',
    appId: '1:796449605451:ios:d78a0d0ec61213d56f8ace',
    messagingSenderId: '796449605451',
    projectId: 'first-app-98ad4',
    storageBucket: 'first-app-98ad4.appspot.com',
    iosBundleId: 'com.example.daftarbelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuqWW9zZRsHjRuUJNzrcqkD8esPhgTsmA',
    appId: '1:796449605451:ios:1d656e0c86d131df6f8ace',
    messagingSenderId: '796449605451',
    projectId: 'first-app-98ad4',
    storageBucket: 'first-app-98ad4.appspot.com',
    iosBundleId: 'com.example.daftarbelanja.RunnerTests',
  );
}
